支持预读buffer固定总容量，避免无限制申请内存导致OOM
tencentyun/hadoop-cos pull request #137
Opened 2024-03-14 13:11 UTC by suninsky

2024-03-28 12:16 UTC, yuyang733 requested changes

2024-03-28 12:42 UTC, suninsky commented on pom.xml
> +    <version>8.3.6-memory-pool</version>
测试的时候用的，后面的commit已经改了。你这个不是最新的

2024-03-28 12:52 UTC, suninsky commented on src/main/java/org/apache/hadoop/fs/MemoryAllocator.java
> +            cleaner.setPriority(Thread.MAX_PRIORITY);
> MAX_PRIORITY

如果走到这个线程的处理逻辑，说明有内存需要由它释放。如果这个线程优先级不高，内存就释放不了。这个优先级弄高也不会产生什么影响，因为正常情况应该都是在sleep状态。这个Thread是参考的hadoop FileSystem里面那个搞的，他也是用的一个Thread在搞，名字叫STATS_DATA_CLEANER

2024-03-29 12:27 UTC, yuyang733 approved these changes

2024-03-29 12:27 UTC, merged