feature: add unit test and convering client-side issues
tencentyun/hadoop-cos pull request #160
Opened 2024-12-10 14:30 UTC by hushengquan

1.线程池单例化
2.HTTP连接池关闭异常捕获，更友好的提示用户
3.tmp目录初始化校验读写权限
4.单元测试

2024-12-12 07:27 UTC, yuyang733 requested changes
线程池不能抽成单例。

2025-01-08 09:51 UTC, yuyang733 approved these changes
LGTM

2025-01-08 12:57 UTC, vintmd approved these changes

2025-01-08 12:57 UTC, vintmd commented on src/main/java/org/apache/hadoop/fs/CosNFileSystem.java
> +        LOG.debug("Filesystem {} is closed", uri);
外层有打印

2025-01-08 13:02 UTC, hushengquan commented on src/main/java/org/apache/hadoop/fs/CosNFileSystem.java
> +        LOG.debug("Filesystem {} is closed", uri);
刚看了下，确实打印了，这里有个需求单让退出打印下。下次提交的时候给去掉

2025-01-09 03:50 UTC, yuyang733 approved these changes
LGTM

2025-01-09 06:23 UTC, merged